### ISSUE TITLE
where to setup the DB info?

### ISSUE THREAD

**Issue by DFF-fred** [thismessagedestructs/ThisMessageDestructs#1]
Hi!

In src/control/preprocess.inc.php there is the following line:
require_once( 'config/config.inc.php' );

but the src folder has no such config folder.  I'll try to set one up and report back if it works.

**Comment by ghost** [comment]
Thanks fred that is definitely an oversight. Added a sample config file under example folder.  In addition to DB info you'll need to generate a couple private keys (32 bit hexadecimal strings) and fill those in the appropriate places as well.

**Comment by DFF-fred** [comment]
Hi again! Thank you for the prompt response. I suppose the DB has some tables and maybe default values. Do you have a sql file to import to set it up?
